version: '3'
services:
  mongodb:
    image: mongo:4.0-rc
    ports:
      - "27018:27017"  
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"  
      - "15672:15672"

